### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by offa** [sspanak/tt9#382]
How about submitting the project to the [official F-Droid](https://f-droid.org/)?

### Additional information

- [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/)
- [How to submit](https://f-droid.org/en/contribute/#submit-applications)

**Comment by offa** [comment]
@sspanak with your ok, I can help with the packaging and submission.

**Comment by sspanak** [comment]
I have very little free time these days, sorry for keeping you wait.

I am all for publishing in F-droid and other alternative stores. I was planning to do it some time ago, I even started [a branch](https://github.com/sspanak/tt9/compare/master...fastlane) for that, but I never had enough time finish it.

I would be happy if you gave me a hand with publishing. My only concern is #366. It may be impossible to keep any custom added words after doing it, which will make a lot of people unhappy. So I'd rather do #366 before publishing TT9 to a broader public. I am not 100% sure, I think it will be possible to preserve the words, but there are no guarantees until I start writing the code.

Anyway, if you are willing to add the fastlane stuff, please, go ahead. I'll merge it, even if we'll publish later. Also, you may want to check my branch. If there is anything useful, it's all yours.

**Comment by sspanak** [comment]
@offa, I have created [a new release](https://github.com/sspanak/tt9/releases/tag/v27.0) and I believe it is good to go. If you still have time and interest in helping with the submission, please go ahead. And let me know if you need me to do anything else to make it happen.

**Comment by offa** [comment]
[rfp](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14512) is on the way :+1:.

**Comment by sspanak** [comment]
Perfect, thank you!

**Comment by sspanak** [comment]
@offa, I have released [v28.0](https://github.com/sspanak/tt9/releases/tag/v28.0). Shall we give the publishing another try? Hopefully, everything is OK this time, but if not, I'll edit the release.

**Comment by offa** [comment]
@sspanak the update check is still broken as a static version code is needed.

**Comment by sspanak** [comment]
Continuing the discussion in Gitlab...

**Comment by sspanak** [comment]
It looks like we've got an approval and F-droid release is finally going to happen. Thanks for the help, @offa!

I'll keep the issue open until the app actually becomes visible.

**Comment by offa** [comment]
… and we need to add the F-Droid badge ;-)

**Comment by sspanak** [comment]
Right! I am looking forward to adding it!
