### ISSUE TITLE
v50.0 problems

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#810]
I found the following bugs (after upgrade and without rebooting):

- "punctuation order" in and out of Groups, **when changed and "saved"** (yeap, i tapped on "save order"), is not respected...

- (small detail) also in the "zero" key config, you say that Space and NewLine are added automatically but in fact it is Space, NewLine **and TAB** (this makes me wish i could disable NewLine and Tab, because i actually don't use them...)

- Shift has some problems as well, apparently:
When i start typing it puts the first letter capitalized (as it should), but when i type the second word, if i press shift (after typing it) it cicles from **all small case** to **First letter cased** then to **all small case** again and only then to **all case**.

- The icon it self, also does not represent the case correctly 
Clarifying:
1 - when i hit Zero/space the shift becomes automatically capitalized as if the Space itself was a **First letter cased** word which could be misleading
2 - second problem: type a word > type space > type a second word (lets call this word A) > hit shift once (to get  **First letter cased**) > hit space > delete last typed word, char-by-char > type another word (lets call this word B). **Result**: it gets the shift used in the **word A**, but when typing the **word B**, it types it **all small case**... so the shift icon is wrong

![Image](https://github.com/user-attachments/assets/d697e597-c63e-45e7-9c9a-d8698927e76f)

I'll see if i find anything else, and see the effects of rebooting the phone...

**Edit: with the reboot issues remain!**

**Comment by sspanak** [comment]
> "punctuation order" in and out of Groups, **when changed and "saved"** (yeap, i tapped on "save order"), is not respected..

That's strange, I am absolutely sure it is the last bug that I fixed yesterday. Please, double check if you are saving them for the English and viewing the list for Portuguese or vice versa.

> also in the "zero" key config, you say that Space and NewLine are added automatically but in fact it is Space, NewLine **and TAB** (this makes me wish i could disable NewLine and Tab, because i actually don't use them...)

If you put these characters in a text field they will displace the text, making it confusing to many users. That's why I decided to add them automatically. I guess I can add a switch to toggle them. Would that work?

> Shift has some problems as well, apparently:
When i start typing it puts the first letter capitalized (as it should), but when i type the second word, if i press shift (after typing it) it cicles from **all small case** to **First letter cased** then to **all small case** again and only then to **all case**.
The icon it self, also does not represent the case correctly

~~There is a weird bug where it selects lowercase twice the first time after installing. After you cycle all the variants once, it should be fine, but please let me know if TT9 keeps doing that. I can look into it in the next version.~~

~~As for the icon, it looks fine on both phones I have with me right now. Are you talking about the status icon next to the clock?~~

Never mind, I got what you mean about Shift.

**Comment by maverick74** [comment]
> > "punctuation order" in and out of Groups, **when changed and "saved"** (yeap, i tapped on "save order"), is not respected..
> 
> That's strange, I am absolutely sure it is the last bug that I fixed yesterday. Please, double check if you are saving them for the English and viewing the list for Portuguese or vice versa.

You're right! In English it shows the order as i selected, but it does not affect Portuguese! In Pt, it does not show the order as i configured it! How can i make it work for both?


> > also in the "zero" key config, you say that Space and NewLine are added automatically but in fact it is Space, NewLine **and TAB** (this makes me wish i could disable NewLine and Tab, because i actually don't use them...)
> 
> That's why I decided to add them automatically.

That makes perfect sense! It's the way it should be! :)

>  I guess I can add a switch to toggle them. Would that work?

Yes, that would do the trick for sure :)


(i've made a few editions on the OP to clarify things for you and other possible readers...)

**Comment by sspanak** [comment]
> You're right! In English it shows the order as i selected, but it does not affect Portuguese! In Pt, it does not show the order as i configured it! How can i make it work for both?

In the Settings, first select Portuguese, then set the order? Doesn't that work?

![Image](https://github.com/user-attachments/assets/8245a4fb-1f89-4d7d-ae03-d3bee0ae4d2b)

**Comment by maverick74** [comment]
> In the Settings, first select Portuguese, then set the order? Doesn't that work?


**Please, stand by while i'll grab a hammer to hit myself in the head with it!!!**


.................I didn't notice the "Language" option on top..............
Sorry about that :( :( :(

**Comment by maverick74** [comment]
I'm probably doing something wrong here as well, but i'm not being able to see the status icon either (the one that shows the language being used)

**Comment by sspanak** [comment]
>Please, stand by while i'll grab a hammer to hit myself in the head with it!!!
.................I didn't notice the "Language" option on top..............
Sorry about that :( :( :(

It has been there forever. 🙂 Either way, if you haven't noticed it, I am sure there will be many more who will miss it too. I'll add the name of the language to the save button, to make it completely clear. 

>I'm probably doing something wrong here as well, but i'm not being able to see the status icon either (the one that shows the language being used)

Have you tried turning it off and on again (I am not joking). 

This release is a complete disaster so far. I'll hold it back for a couple more days. Fortunately, I haven't released on Google yet.

**Comment by maverick74** [comment]
> It has been there forever. 🙂 Either way, if you haven't noticed it, I am sure there will be many more who will miss it too. I'll add the name of the language to the save button, to make it completely clear.

👍!
But sometimes I do miss things, so it's my fault!

> > I'm probably doing something wrong here as well, but i'm not being able to see the status icon either (the one that shows the language being used)
> 
> Have you tried turning it off and on again (I am not joking).

Yes a few times! I also checked permissions! Unless I'm on the wrong place... isn't it in 

Settings - Appearance (or similar) - Status Icon 

???

> This release is a complete disaster so far.

Oh no!!! I completely disagree!!! 

It brings A LOT of great new features, bug fixes, technical and language improvements and code clean ups!
It's a **huge** release!
And if you look to it in terms of % of issues I don't believe it is that much of a disaster! 

You've made a tremendous amount of work (and indeed GREAT WORK!!!) even if it has a few things that still need a small tweak, it is to all measures a GREAT AND AMAZING RELEASE!!!

And it is to you we all must thank for this!

**Comment by sspanak** [comment]
> > > I'm probably doing something wrong here as well, but i'm not being able to see the status icon either (the one that shows the language being used)
> > 
> > 
> > Have you tried turning it off and on again (I am not joking).
> 
> Yes a few times! I also checked permissions! Unless I'm on the wrong place... isn't it in
> 
> Settings - Appearance (or similar) - Status Icon
> 
> ???

Yes, that's the one. I am not sure why you don't see it. It may be yet another Xiaomi quirk. Perhaps, you can try installing [k9t9](https://github.com/danielshorten/k9t9/releases)? It is designed to work only with a hardware keyboard, so it doesn't have a UI, but it displays an icon by default. It will be e good test if your phone supports status icons at all. Just switch to it and click on some text field to see if it works.

> > This release is a complete disaster so far.
> 
> Oh no!!! I completely disagree!!!
> 
> It brings A LOT of great new features, bug fixes, technical and language improvements and code clean ups! It's a **huge** release! And if you look to it in terms of % of issues I don't believe it is that much of a disaster!
> 
> You've made a tremendous amount of work (and indeed GREAT WORK!!!) even if it has a few things that still need a small tweak, it is to all measures a GREAT AND AMAZING RELEASE!!!
> 
> And it is to you we all must thank for this!

Thank you. I mean... you have no idea. I've been trying to publish it for the past 10 days and every day I find a critical bug (well, from my perspective). But now, I have fixed the problems with Shift and I think it is good to go. I really appreciate the immediate feedback and I will appreciate if you give [the next release candidate](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v49.117.apk) a try. Anyone else willing to test, you are also welcome.

I have NOT added the buttons for removing Tab and Newline from the special character list. I can do this in the next version. I don't think it is extremely important to do it in v50.0.

**Comment by maverick74** [comment]
> It may be yet another Xiaomi quirk.

Yeap... it seems that way! K9T9 does not show the icon either! I'll try to investigate more about this later! But since we also have the indication on the key itself it's not that important! (btw, is the language code EN/PT suppose to be that low on the key? They look a bit too much to the bottom...)

> I have fixed the problems with Shift and I think it is good to go.

Well... there are a few things I'm not sure if they are supposed to work this way! Lets see:

1 - when I hit space or when I select a word (even without hitting space), before I start to type a new one, shift is always on (e.g.: in the middle of a sentence) which I don't think makes much sense!

2 - if I type a word in CAPS, hit space, disable the caps-lock but, instead of typing a new word, delete the space I just inserted - it will, once again, re-enable the CAPS-LOCK I removed and continue to write everything in CAPS

3 - I just noticed another weird behavior! To reproduce: type the word "caps"  hit OK twice (to get 2 new lines), then hit delete once!

Result: It will move to the caps line (even if in theory I would have to hit delete twice to get there) and it will insert a "C" before the CAPS word

> I don't think it is extremely important to do it in v50.0.

Oh no! That's not that important! I can wait for the next version! 🙂

**Comment by sspanak** [comment]
> > It may be yet another Xiaomi quirk.
> 
> Yeap... it seems that way! K9T9 does not show the icon either! I'll try to investigate more about this later! But since we also have the indication on the key itself it's not that important! (btw, is the language code EN/PT suppose to be that low on the key? They look a bit too much to the bottom...)

I don't think it's a big deal. The status icons are not intended for touchscreen phones. The function is not well-thought, so I wouldn't be surprised if they decided to drop it entirely from their Android variant.

> > I have fixed the problems with Shift and I think it is good to go.
> 
> Well... there are a few things I'm not sure if they are supposed to work this way! Lets see:
> 
> 1 - when I hit space or when I select a word (even without hitting space), before I start to type a new one, shift is always on (e.g.: in the middle of a sentence) which I don't think makes much sense!
> 
> 2 - if I type a word in CAPS, hit space, disable the caps-lock but, instead of typing a new word, delete the space I just inserted - it will, once again, re-enable the CAPS-LOCK I removed and continue to write everything in CAPS
> 
> 3 - I just noticed another weird behavior! To reproduce: type the word "caps" hit OK twice (to get 2 new lines), then hit delete once!
> 
> Result: It will move to the caps line (even if in theory I would have to hit delete twice to get there) and it will insert a "C" before the CAPS word

1. This is not a bug in the sense that it works the way I intended. And it is actually what is happening behind the scenes. When in 'auto' mode, TT9 switches the text between every word. Anyway, I understand this is not so useful information from user perspective. The question here is what more logical? In the case when special characters (including emojis, space, etc) are displayed or nothing is displayed, I can either enforce lowercase icons or keep the previous, regardless of the internal state. My intuition says keeping the previous makes more sense, but I'll experiment with both variants and keep what feels better.
2. This is correct. TT9 has been working like this since v38.0 when I added the Word Recomposing option. When you delete a word, it attempts to match its text case and after that, when you start typing a new one, it remains in that text case. Since uppercase takes priority over all others, words in uppercase will switch TT9 to uppercase. I do not plan to change this.
3. This is a bug and I am aware of it. However, I decided to leave it for version 51.0 because typing many new lines, then going back to edit the words before the new lines is not a common scenario, so I won't bother too many people. It happens with all words, not just "caps".

**Comment by maverick74** [comment]
Agreed :)

regarding 2 and 3 they're of such importance i didn't actually noticed any of them before... ahahah

then.. i think it's ready for ship! At least from my POV :)

**Comment by maverick74** [comment]
well... let me add another detail (that may also be intentional): when typing in small caps and you change language it seems to always capitalize the first letter of the word... (not something worth fixing for this release either, if you consider it a bug...)

**Comment by sspanak** [comment]
If you are willing to test the final, final version [v49.118](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v49.118.apk), please go ahead. It makes Shift and the status icon (that you can't see) more consistent. I'll give it 24 more hours, then I will pronounce it ready. 

> well... let me add another detail (that may also be intentional): when typing in small caps and you change language it seems to always capitalize the first letter of the word... (not something worth fixing for this release either, if you consider it a bug...)

I can't reproduce this one. I would have noticed it, I use more than one language and I switch between them all the time. Does it happen in all apps?

**Comment by maverick74** [comment]
> If you are willing to test the final, final version 

I'm always up for testing new software versions :)
I'll try and if i find anything weird i'll report back. But so far all looks good...


> I can't reproduce this one. I would have noticed it, I use more than one language and I switch between them all the time. Does it happen in all apps?

yeah... apparently it happens in any app. I can reproduce it anytime easily! 

I type, for example the sentence (in english) "_**A test**_" (it's worth noting that i do not select the tt9 suggestion - the word is still underlined when i switch languages!!!) and when i change to Portuguese the "**test**" word becomes " _**T**est_ " (with the suggestions showing "**Teste**") but with first letter capitalized.

Same thing if typed in Pt and then change to En.

EDIT: because I don't know if you noticed it above:

![Image](https://github.com/user-attachments/assets/d3167a52-ad66-47af-87b7-76589fc37c40)

**Comment by sspanak** [comment]
> I type, for example the sentence (in english) "A test" (it's worth noting that i do not select the tt9 suggestion - the word is still underlined when i switch languages!!!) and when i change to Portuguese the "test" word becomes " Test " (with the suggestions showing "Teste") but with first letter capitalized.
>
> Same thing if typed in Pt and then change to En. 

Alright, I was able to reproduce it with English and Portuguese. I'll fix it in the next version. 

> EDIT: because I don't know if you noticed it above... 

Yes, but I forgot to reply, sorry. 

The letters are shifted down deliberately. On some screens and with when the keyboard is set not to be so tall, I've found that the letters overlap with the planet icon, so I had to move them down a bit. This is especially true for Arabic alif, which looks like Latin I or small L, but it is even taller. In the future, I may try to adjust it better.

**Comment by maverick74** [comment]
Another question:

why can't I, in the middle of a sentence, enable shift just for the first letter - for the next word?

Right now, when I am in the middle of a sentence, if I go to shift for the next word I only get "no caps" or "ALL CAPS" (before selecting space) and "First Caps" and "ALL CAPS" (after hitting space)

after getting a new line, for example, I don't get an option to start a sentence with "no caps"! I have to first type the word and then select what I want!

I believe what's expected is that the user can select any of the 3 states either before during or after typing the word!

well... honestly, I think it's a lot more complicated than this... but I guess you get the point...

DISCLAIMER: I am REALLY - *REALLY* - SORRY for being A TERRIBLE PAIN IN THE ***! You probably won't want to here from me in the next months! Ahahah! (But, really: Sorry! I actually feel a bit bad!)

**Comment by sspanak** [comment]
> why can't I, in the middle of a sentence, enable shift just for the first letter - for the next word?

It's because Automatic Capitalization is on. When enabled, TT9 decides what is the text case of the next word so you don't have to think about it. Of course, sometimes it guesses it wrong, that's why I have allowed correction after you type a word and you notice it is wrong. It doesn't make much sense to change the text case beforehand because you don't know if it will be wrong or not.

If you want full control in your hands, you have to disable the option.

> I am REALLY - REALLY - SORRY for being A TERRIBLE PAIN IN THE ***! You probably won't want to here from me in the next months! Ahahah! (But, really: Sorry! I actually feel a bit bad!)

Absolutely not! Your comments and feedback have been most useful. Please allow me to quote from memory a somewhat similar conversation about Shift key with another user:

_User_: THIS KEYBOARD IS STUPID! IT TYPES ONLY CAPTIAL LETTERS! SEE, I AM TYPING CAPITAL LETTERS BECAUSE I CAN'T TYPE SMALL LETTERS. FIX YOUR APP!
_Me_: To change the text case, press the Shift key. It's the third key on the left, it has an upward arrow on it.
_User_: This is the most unintuitive app ever! It has zero predictive capabilities and zero usability! It is unclear what the keys do and there is no tutorial. I will uninstall it and install Touchpal.
_Me_: wtf?!

... and this is at least half the feedback that I am getting. I understand there are many problems, many things to improve, but they won't tell what they are unhappy about, and/or they just say Touchpal is the greatest and I should learn from it. I am really, really looking forward to constructive criticism like yours! It helps me, and it helps the community. There is no reason to feel bad about it.

P.S. the final-final v50.0 is out! 

P.S.2. The not-so-urgent bugs, I've left for v51.0: the double letters after deleting newlines; words becoming capitalized when switching between languages; options to disable Tab and Newline from the 0-key list; Fix the scissors icon (someone reported it looked weird on some device that I don't remember). Please, let know if I have missed something.

**Comment by maverick74** [comment]
> Please allow me to quote from memory a somewhat similar conversation about Shift key with another user:
> 
> _User_: THIS KEYBOARD IS STUPID! IT TYPES ONLY CAPTIAL LETTERS! SEE, I AM TYPING CAPITAL LETTERS BECAUSE I CAN'T TYPE SMALL LETTERS. FIX YOUR APP! _Me_: To change the text case, press the Shift key. It's the third key on the left, it has an upward arrow on it. _User_: This is the most unintuitive app ever! It has zero predictive capabilities and zero usability! It is unclear what the keys do and there is no tutorial. I will uninstall it and install Touchpal. _Me_: wtf?!

W... T... F... ?!?! 😲😲😲

You must be joking!!! Is this for real?!?! 

Who the f*ck makes such a comment?!?!

wtf is wrong with people these days?!?! 😠


> P.S. the final-final v50.0 is out!
> 
> P.S.2. The not-so-urgent bugs, I've left for v51.0: the double letters after deleting newlines; words becoming capitalized when switching between languages; options to disable Tab and Newline from the 0-key list; Fix the scissors icon (someone reported it looked weird on some device that I don't remember). Please, let know if I have missed something.

Great! Installing...

**Comment by maverick74** [comment]
Regarding this:

> It doesn't make much sense to change the text case beforehand because you don't know if it will be wrong or not.
> 
> If you want full control in your hands, you have to disable the option.

lets see if this makes any sense to you:

A middle ground where the user, with Automatic Capitalization ON, could manually override it.

case: i have **Automatic Capitalization** ON && **First Letter Capitalization in each new line** also ON

1. If, for some reason, i want my next sentence (which i'll make in a new line) to be ALL CAPS: presently i can do this easily with just _a tap on shift_ before typing the word! 
2. If i want just the first letter, that's even easier: it's the default behavior in each new line with this settings

3. However, **i can't tap shift _twice_**, _before typing the word_, to get them all **in small caps**. And users are probably expecting this because of the behavior of 1.

Yeah, there's a pretty easy workaround for this: just type the word first and then change it... **and it's great to be possible to change it during and after typing a word, as it is**. But... why not also **before**, like in 1?

User could disable the Automatic Capitalization - permanently - like you said, but it will loose the Automatic Capitalization in general because of the special cases. Which is probably not the desired effect!

I, personally, do not have a problem with changing this at all after typing (it was just a question of memorizing the workflow). But the workflow described for 3. will probably be "the expected workflow" by users, considering 1. ...

**Comment by sspanak** [comment]
I guess you are right. I'll see if there is an easy way to do it.

**Comment by sspanak** [comment]
Hey, @maverick74, are you up for testing [v50.17](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.17.apk)? It addresses everything else that we discussed here, including the problem where the text case may change after deleting a word in uppercase. I think TT9 works much more predictable now but it would be nice to confirm it we are on the same page.

**Comment by maverick74** [comment]
Installing!!!

Will test and report asap 🙂

Edit: btw, v50.0 so far as been absolutely terrific (even with the issues talked here its been a very smooth experience!!!)

**Comment by maverick74** [comment]
At a glance: 

hiding tab and enter/new line works great!

The caps thing not so great! Here's what I found:

- in a new line, before typing a word, I select I will want it all small caps! This works well! But if now I type a new line it won't respect the setting for First Caps in a new line! (it keeps the setting previously selected and I was expecting it would get the First Caps setting!)! In other words: if "**Automatic Capitalization** ON or **First Letter Capitalization in each new line** also ON, then when we get to a new line it should forget my previous setting!

- now i'm getting a weird behavior regarding shift! here's how i replicate it:

1- in english dictionary, in the middle of a sentence, type "tab" (all in small caps)
2- before accepting the word hit shift to change the caps of the "tab" word

Here, the word vanishes!!! You getting the same result?

(will continue to test it! If I find something else I'll edit this post and add it - unless you prefer new comments for any new issues)

**Comment by sspanak** [comment]
> in english dictionary, in the middle of a sentence, type "tab" (all in small caps)...

This is absolutely weird! I can reproduce it only when I type the word "tab" in small letters. I'll see what's wrong with that.

> in a new line, before typing a word, I select I will want it all small caps! This works well! But if now I type a new line it won't respect the setting for First Caps in a new line! (it keeps the setting previously selected and I was expecting it would get the First Caps setting!)! In other words: if "Automatic Capitalization ON or First Letter Capitalization in each new line also ON, then when we get to a new line it should forget my previous setting!

Ah, yes, I forgot to test the "Capitalization on New Line" option. I'll fix it.

> btw, v50.0 so far as been absolutely terrific (even with the issues talked here its been a very smooth experience!!!)

Actually, from Google Play, I am getting a lot of crash reports when loading a dictionary and when pressing Shift. I can't normally reproduce any of them, I don't know how these people click, but I definitely see the mistakes in the code. This is why I'll probably do an intermediate release before v51.0, only for Google users.

> (will continue to test it! If I find something else I'll edit this post and add it - unless you prefer new comments for any new issues)

If I have replied, I usually don't go back to see if someone has edited their comment after my reply. I expect new information to follow my comment, like a normal conversation. If I haven't replied, it's OK to edit your comment. And if we are both typing at the same time, like a couple of days ago... well, we'll figure it out.

My perception is you do as I described and it is perfectly comprehensible. Keep it up! 🙂

**Comment by sspanak** [comment]
I have tested and found no technical problems. Again, the problem with lowercase is what makes sense. When the user selects uppercase, then it is clear that TT9 should remain in uppercase until Shift is pressed. 

However, when it comes to lowercase, I agree the rules should be more relaxed. I tried to imagine the possible scenarios when I would expect not to change the text case myself and I came up with this list:
- After a new line (as you suggested)
- After starting a new sentence (i.e. after `?`, `!` or `.`). To me this is identical to starting to type after a new line.
- After erasing all text. Assumption is, you want to start over and type everything from scratch, so TT9 also starts over.
- After the app performs some action to clear or reset the text. For example, in a chat app, after you have sent a message and the text field has become empty, TT9 will also "reset" and start the first word with a capital letter. It is nearly identical to starting a new sentence.

What do you think?

**Comment by maverick74** [comment]
> What do you think?

Yes, I believe that makes sense!

> from Google Play, I am getting a lot of crash reports

This is actually weird... I have occasionally experienced some crashes but I always attributed them to the apps I'm using (e.g. teams, firefox, etc) or to my old phone, not to tt9... 

but i also can't find a "padron" to replicate them...

**Comment by sspanak** [comment]
Alright, here comes another update. This must be The One, [v50.19](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.19.apk). It fixes the problem with the word "tab" and adjusts text case automation according the list of rules above.

**Comment by maverick74** [comment]
Almost there but not "**_The One_**"! Sorry!

1. In a new line, if i, before typing, set shift to **all small caps**, it does not respect it and still sets it to "**First Letter In Caps**"

2. also, if i hit "." or "?" or "!" it correctly starts, after, with "**first letter caps**", but if i hit ".." or "..." then after it is continues in "**all-small-caps**". **Is this a bug or is it supposed to work like this?**

**Comment by sspanak** [comment]
1. Perhaps, you still have "Automatic Capital Letters after a Newline" on? If so, it sounds correct to me, because the automation rule kicks in after typing the newline. I could potentially add an exception if you have pressed Shift right before typing a newline but this is quite complicated to do. And then I will have to cover cases when you have pressed Backspace or you have pressed some other key, then retyped something and so on and so forth. It's overengineering from my perspective. I can't do micro-optimizations forever, sorry.
2. This is correct. An ellipsis: `...` or `..`, does not usually end a sentence, so the next word should not normally start with a capital letter. It is possible, of course, but I assumed the more common scenario is when you want to represent a pause or an incomplete thought. And since I can't do a grammatical analysis of the text, you will have to press Shift, if you need to start a new sentence.

In summary, I can't provide full automation. Do not expect TT9 to be able to read your mind and adjust everything for you.

Btw, you may or may have not noticed the following problem: if you try to type "Oh, no", it incorrectly becomes "Oh, No". This is a problem that I will definitely fix.

**Comment by maverick74** [comment]
1. hum... i didn't express well enough, i believe... 

I'll try again! 
First lets clarify: I do have "**Automatic Capital Letters after a Newline**" ON

-Now, i'm typing a sentence...
-I end it and hit Enter/New Line.
-In the New Line, the "**Automatic Capital Letters after a Newline**" kicks in, so that the first letter of the next word i'll type is capital. Everything right so far! It's the expected behavior.
-However this is not what i want to do _this time_. This time i want an exception to the rule: so, in this new empty line, before i start typing my first word, i go on and press shift twice to set it to **all small caps**.
-Shift key _does indicate_ it is in **all small caps** mode but...
-when i start typing it gets the **First letter in capital** (even when shift indicated otherwise)
-so, it doesn't comply with what i intended, neither does it comply with the mode shift indicated

**note 1:** i don't expect it to remember this if i press backspace or anything else as complicated as you mention. I just want a temporary - one shot - exception to the rule for this "hypothetical" sentence.

**note 2:** this **is not** a must have or anything like that. This is a brutally-small detail. But i do believe it is the expected behavior and sometimes "the small details _are the source_ of problems"



2. OK. I was expecting you could say that! But since this could not be what you intended, i decided to report it in case it was not the expected.

> Btw, you may or may have not noticed the following problem: if you try to type "Oh, no", it incorrectly becomes "Oh, No". This is a problem that I will definitely fix.

huuuummmmmmm.......... i'm not being able to reproduce this here in either dictionary!!!

**Comment by sspanak** [comment]
1. I see. Indeed, I misunderstood what you meant but it is still the same situation. Making exceptions to the "Automatic Capital Letters after a Newline" is very difficult. I will prevent Shift from working at the beginning of a line when the option is on, to avoid confusion.
2. All good.
3. Yes, it seems to only happen in Bulgarian. I just translated the problematic phrase to English but later I saw it is fine in English. Never mind, it's one of those errors. It's a good thing I use 4 languages.

**Comment by maverick74** [comment]
> 1. I see. Indeed, I misunderstood what you meant but it is still the same situation. Making exceptions to the "Automatic Capital Letters after a Newline" is very difficult. I will prevent Shift from working at the beginning of a line when the option is on, to avoid confusion.

No problem! We can always change caps after typing the word 🙂

**Comment by maverick74** [comment]
> 1. I will prevent Shift from working at the beginning of a line when the option is on, to avoid confusion.

But please, keep the possibility of setting ALL CAPS ON before start typing, as it is now!

**Comment by sspanak** [comment]
> But please, keep the possibility of setting ALL CAPS ON before start typing, as it is now!

It is there. Here is the final final final variant: [v50.21](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.21.apk).

**Comment by maverick74** [comment]
> It is there. Here is the final final final variant: [v50.21](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.21.apk).

In a new line, yes it does not allow anymore to disable shift. Looks OK now!
But after a . or ? or ! it still allows it and then forces a first letter caps. 
But i don't believe it's something worth fixing... it's a small detail even more "_invisible_" than when typing a new line.
but i'll leave that decision to you :)

**Comment by sspanak** [comment]
> But after a . or ? or ! it still allows it and then forces a first letter caps.
But i don't believe it's something worth fixing... it's a small detail even more "invisible" than when typing a new line.
but i'll leave that decision to you :)

I fixed that too. With this, I believe all discussed problems are solved and I can close the bug. As always, you are welcome to report more problems, just create a new bug, so I can notice it faster.

**Comment by maverick74** [comment]
I just noticed that if I want to type a name in the middle of a sentence I can't shift-before-type to get the word with a "first capital letter"!

And this, I believe, is a bit important because it's an expected function (it does indicate shift is in the right mode, however... but then ignores it)

This shift thing is tricky as hell, I must say... sorry for so many reports... 🙁

**Comment by maverick74** [comment]
Thing is: by default I think tt9 should behave as it does (it works wonderfully for general purpose) but the exceptions are still not as - I believe - a regular user is expecting (I maybe wrong, naturally!!!)!

I think regular user expects to be able to overwrite the default at any time by just hitting shift either after typing a word (as it does already) or before (which is the case I think is not matching the behavior of the former!)

I believe user expects consistency between both cases, specially because typing habits are a personal thing

E.g.: there are users where the habit is to, before typing, indicate how they intend the word to be typed (maybe this comes from using PCs...) while others will prefer to type the word first and then set the look of it!

But in both ways, user should have the same options and be able to get to them using the same path!

Maybe this doesn't make any sense to you, or maybe it's a very big hurdle to implement...

In any case, I don't intend to be a PITA, you actually have already done A LOT!!!! And I'm truly grateful for everything you've done!

I'm just sharing "2 cents" about this! Please, don't take it bad 🙁!

Again: thank you for all you've already done - all alone!!!

**Comment by sspanak** [comment]
> I just noticed that if I want to type a name in the middle of a sentence I can't shift-before-type to get the word with a "first capital letter"!

This isn't good, I'll look into it.

> Maybe this doesn't make any sense to you, or maybe it's a very big hurdle to implement...

I understand and it makes sense to me but it is difficult to implement. I'll see what I can do. And don't worry, I am not mad at you. The reason I am in a hurry is because the number of crash reports on Google is increasing.

**Comment by maverick74** [comment]
Yeah... i'm experiencing some occasional crashes as well, but they seem random. I can't replicate them at will! I've not been able to find a cause so far...

It also happened twice that while i'm typing it "eats" one of my letters but if i delete the last letter typed it gets it back...

Remember: take all this with a grain of salt and consider it only if there is more reports because _it maybe from my phone_

> but it is difficult to implement.

I'm going to shot an idea that may help (most surely won't help anything, but just in case...): 

would it be simpler if, when we hit shift, it would "temporarily" disable - for that word alone - the automatic capitalization rules?

**Comment by sspanak** [comment]
> Yeah... i'm experiencing some occasional crashes as well, but they seem random. I can't replicate them at will! I've not been able to find a cause so far...

Google can connect the crashes to the actual files and the specific lines of code that caused it. They get it right only half of the time but they have helped a lot so far. It's one cool thing about Google Play! So, don't worry about the mysterious crashes that occur only at full moon and when the light in the kitchen is on. 😄 

> It also happened twice that while i'm typing it "eats" one of my letters but if i delete the last letter typed it gets it back...

This could happen with any word. Some time ago, in attempt to prevent typing lag, I've decided to abort database requests that take too long. This allows immediate response when you press a key but may cause missing letters. It's usually OK when in the middle of the word and you are typing quickly because on the next key press you will get the next set of words and you will not notice the wrong result. But, sometimes, if you make a longer pause, or if it is the last letter of the word, you may get incorrect suggestions.

In my opinion, quick response is better than lag, even when the results are weird sometimes. In my tests, on my older phone, the lag reached above 0.5 seconds per key press, especially when the phone was doing something else in the background. So, I chose the lesser of two evils.

> would it be simpler if, when we hit shift, it would "temporarily" disable - for that word alone - the automatic capitalization rules?

I wanted to avoid this but it is the only way, I think. I did it in the latest final [v50.24](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.24.apk). Go ahead and try it out.

**Comment by maverick74** [comment]
> the latest final [v50.24](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.24.apk)

**THE ONE**!!!!!!! 🤣🎉🍺

It seems to be working just perfect

(at least from my tests in the last few hours)

---

The only thing _weird_ that can be pointed is that when typing in all small caps, in the middle of a sentence, and we intent the next word to have the first letter in caps it follows this order:

all-small-caps (where we are) > ALL CAPS > all small caps (again) > First Letter Caps

But, if I understand it correctly, then this is probably the result of passing from:

AUTOMATIC MODE 
[all-small-caps (where we are)]

-> (that then passes to)

MANUAL MODE (which has a pre-set order)
ALL CAPS > all small caps > First Letter Caps

If it's this the origin of the behavior as I suppose it is, then it's the price to pay for the feature and I'm perfectly happy with it 😀

**Comment by sspanak** [comment]
> THE ONE!!!!!!! 🤣🎉🍺
It seems to be working just perfect

Finally! I'll test some more when I do French lessons this evening, and hopefully, it will be good to go tomorrow.

> The only thing weird that can be pointed is that when typing in all small caps, in the middle of a sentence, and we intent the next word to have the first letter in caps it follows...

Yes, the reason is the automatic mode is displayed as one of the manual modes, and when you switch out of it, you seemingly go one step back. But I thought I've fixed this. I can't reproduce it under any circumstances. Could you please provide a sample sentence? Maybe it is language-specific.

**Comment by maverick74** [comment]
> when I do French lessons this evening

French lessons?!?! Irrrkkkk 😭😭😭
3 years I had of that... what a nightmare!!!
There is only one more language I would love to learn: Latin (ecclesiastic version)




> I can't reproduce it under any circumstances.

I've surely didn't explain well enough (again! Sorry for my bad English).
It happens in any language (english or portuguese)!

1- When writing a sentence (such as this one), in the middle of the sentence, shift shows itself as in all-small-caps mode (an "empty" arrow)
2- now hit shift AND IT ENTERS ALL-CAPS MODE
3- Hit it again and and it will show **not a filled arrow** - that would indicate the First-Letter-In-Caps mode - but instead it shows, again, the empty arrow, that indicates the all-small-caps mode!
4- only if you hit it another time, then it will get to the First-Letter-In-Caps mode

So, we get to all-small-caps mode twice!!! I'm almost sure this is expected... but just in case it isn't...

---

Now... while writing this I've noticed yet another detail - easy to reproduce:

1- Just type: "I've"
2- While "'ve" is still underlined, try to set it to ALL-CAPS

Result: you can't! (probably because of the ' )

**Comment by sspanak** [comment]
> French lessons?!?! Irrrkkkk 😭😭😭
3 years I had of that... what a nightmare!!!
There is only one more language I would love to learn: Latin (ecclesiastic version)

I don't understand why everybody keeps talking like this about French. You people don't understand, it takes time and dedication to learn to love the language. You just need to be more patient and it will work out one day. 😄

> I've surely didn't explain well enough (again! Sorry for my bad English).
It happens in any language (english or portuguese)!
...

You did but it doesn't happen on my phone or in the emulator. Do you mean like this:

https://github.com/user-attachments/assets/24dbcf82-9e7d-4f28-88bd-75384305fdcf


> Now... while writing this I've noticed yet another detail - easy to reproduce:
>
> 1- Just type: "I've"
> 2- While "'ve" is still underlined, try to set it to ALL-CAPS
> 
> Result: you can't! (probably because of the ' )

This bug has been around for a long, long time. I've noticed it shortly after adding Dutch. This means 2 years ago or so. At one point I was going to fix it but then I forgot about it. I am writing it down this time. It isn't something critical but it would be nice to have Shift working in this case too.

**Comment by maverick74** [comment]
> it doesn't happen on my phone

What kind of wizardry just happened here?! All of the suddenly i'm not being able to reproduce it at will anymore...... it now happens seldom and randomly instead of always...... 🙁

well lets put this on hold while i'll beat the horse... will clean up and reboot the phone and do some other things and see the result! If I a way to replicate it i'll report back! Sorry about it!

> I am writing it down this time

👍

> takes time and dedication to learn to love the language.

After 3 years I don't think it's a question of time... dedication... on the other hand..... ahahah 🤣! Maybe that's where it went south!!! 🤣

**Comment by maverick74** [comment]
OK, here we go:

https://github.com/user-attachments/assets/7964b175-4b99-4449-8438-eb008cab92fd

After the space, watch the shift cycle that happens from around ~8sec to ~12sec!

**Comment by sspanak** [comment]
Thanks! I think I got what's wrong.

**Comment by maverick74** [comment]
OK, an update from the last 24h use:

so far, from my use, i didn't find anything else!

🙂

**Comment by sspanak** [comment]
Here is on more update, [v50.27](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.27.apk). It should fix all remaining problems with Shift.

> so far, from my use, i didn't find anything else!

You'll get such a boring upgrade to v51.0. There will be no functional changes and only 2 new English words.

**Comment by maverick74** [comment]
> You'll get such a boring upgrade to v51.0.

It's a "stable release" ahahah 🤣

[testing...]

**Comment by maverick74** [comment]
There's still something about it:

https://github.com/user-attachments/assets/ac44ea67-4efc-4afe-b719-967e1c2457e8

When typing in small-caps shouldn't the shift sequence be small-caps + First Caps + ALL CAPS?

(note ~7sec)

**Comment by sspanak** [comment]
Well... no. When you are typing a word, TT9 attempts to use its text case to determine what comes next (that's what I did in the v50.27). But if you start typing a space or another special character, it has no text case, so TT9 falls back to the initial selection, which was First Capitals. In automatic mode, this case is a bit magical. But if you enforce lowercase and uppercase, the next option should be as expected.

**Comment by maverick74** [comment]
> Well... no. When you are typing a word, TT9 attempts to use its text case to determine what comes next (that's what I did in the v50.27). But if you start typing a space or another special character, it has no text case, so TT9 falls back to the initial selection, which was First Capitals. In automatic mode, this case is a bit magical. But if you enforce lowercase and uppercase, the next option should be as expected.

I was typing in all-small-caps at ~8sec and i _tapped shift just once_ and it went strait to ALL-CAPS, 
but if you look at ~29sec i was also typing in all-small-caps, but when i hit shift, this time, it goes to First-Letter-Caps...

This is expected?? If so, i'm not getting it... :)

**Comment by sspanak** [comment]
Never mind, I have found a way to fix it. Here is [v50.30](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.30.apk) for you to test.

Note that, in this version you may notice the Shift status is displayed with a slight lag sometimes. I did this to prevent too much visual changes, in other words, high battery usage. So, when you press many keys very quickly, TT9 will wait until you stop pressing, and then update the status.

**Comment by maverick74** [comment]
I'm sorry! What I was pointing out has not changed 🙁

But I'm starting to think I'm getting it wrong or i'm not being able to point out the issue clearly... 

Here's another try (in parts):

When in a new line tt9 starts with automatic mode! You mentioned that automatic mode is "kind of" another shift state (like all-small-caps, ALL CAPS, Capital First Letter)

Correct???

Now, lets see if I got the rest right: 

In **Automatic mode** it assumes the first word of a new line has a "capital first letter" and the rest are all small-caps! 

But every time we accept a word/space, since it doesn't know what we're about to write next, tt9's automatic mode always enters in "capital first letter" mode

Is this correct so far???

However when we - manually - choose a word to be in ALL CAPS 
**and then we back to all-small-caps**, 

it stays in "all-small-caps" mode and does not return to Automatic Mode (where "capital first letter" mode gets chosen in every word)

Is this also correct?

**Comment by maverick74** [comment]
If all the above is correct then it seems logic to me that

in automatic mode - when a word/space is accepted and it automatically gets to Capital-first-letter mode - if we press shift it gets strait to ALL-CAPS mode (because the previous state was _actually_ the automatically-imposed Capital-first-letter mode)

While after we force **ALL-CAPS** and then change it to **all-small-caps** the next mode is indeed **Capital-first-letter** mode because we exited the "automatic mode" and it is not recovered for the new words in that line

This would explain the perception that - when we're in **automatic mode** **before** accepting a word/space - we go strait from all-small-caps to ALL CAPS (skipping Capital-first-letter mode - because we barely see it)

(from what i understand, we can re-enter automatic mode by selecting Capital-first-letter mode...)

**Comment by sspanak** [comment]
> Here's another try (in parts)... (comment 1)

Yes, all is correct, except that small letters are enforced only until the end of a sentence. Then, it will go back to automatic again.

> If all the above is correct then it seems logic to me that (comment 2)

Not anymore. In v50.30, I have fixed exactly this, except maybe in very specific cases. From the top of my head, there are three possible cases: 1) When you are typing a word; 2) When you are typing a special character; 3) When you are not typing anything, just pressing Shift. In all these cases, you should be able to cycle the text cases in the same order. Note that some words can be only in uppercase and lowercase, for example, "IBM", but I don't think we are discussing them here.

So here is a longer video from my phone. It shows different situations in which you can toggle the text case. Ignore the first "nothing", I got distracted at the point.

https://github.com/user-attachments/assets/f9815e06-6161-4193-b9c8-91e39d45ec57

Does it work differently on yours?

**Comment by maverick74** [comment]
There's a difference between your 25th second and my 7th second!

See my record:

https://github.com/user-attachments/assets/2026b3b4-b64b-4617-8e99-70fb931af431

It jumps strait from all-small-caps to ALL CAPS (skipping First-Letter-Caps)

**Comment by sspanak** [comment]
Sorry, wrong APK. I have built a new one: [v50.31](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.31.apk). This one should really fix the problem.

**Comment by maverick74** [comment]
> I have built a new one: [v50.31](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v50.31.apk).

**T.H.E. O.N.E. !!!**

(**thank you SO MUCH** for standing by for sooooooooo _many_ replies i've made... i'm really - **trully** - sorry!!! This must have been a challenge to you, not technically, but a boring one)

**Comment by sspanak** [comment]
And thank you for the persistence! 

Some time ago, I've noticed many other keyboards light up and turn off the Shift key as you type. I thought this is super cool and I should do it too, but it turned out to be more difficult than I was anticipating. I wasn't going to do it perfect without you. Thanks for noticing the small details that I kept missing all the time. You shouldn't be sorry, you have helped A LOT.

I'll probably keep this open a couple of days. I do not plan to do any more code changes in this version, only language improvements, so I don't expect any new bugs to pop up. Either way, I'll wait for "v51.0 problems".

**Comment by maverick74** [comment]
Off-topic:

https://blog.cyrneko.eu/everyone-should-copy-thunderbird

Maybe a popup or something like it...?

**Comment by sspanak** [comment]
I'll see about this. Google doesn't like donations. In fact, several months ago, they wanted to ban the app from the Play Store because I don't offer "regular" paid features instead.

**Comment by maverick74** [comment]
> I'll see about this. Google doesn't like donations. In fact, several months ago, they wanted to ban the app from the Play Store because I don't offer "regular" paid features instead.

Yeah... the "greedy google patch" 🤣🤣🤣 i remember that!!!

I laughed a lot about that name 🤣🤣🤣

even if _greedy google_ does not allow it, maybe you could use it on f-droid... anyway, it's Just an idea :)
